---
- name: Rundeck - PostgreSQL | make server lib directory
  file: >
    group=rundeck
    mode=0655
    owner=rundeck
    path=/var/lib/rundeck/lib
    state=directory
  tags:
    - rundeck
    - directory
    - postgresql

- name: Rundeck - PostgreSQL | download postgreSQL jdbc driver
  get_url: >
    dest=/var/lib/rundeck/lib/postgresql-9.3-1101.jdbc3.jar
    url="http://jdbc.postgresql.org/download/postgresql-9.3-1101.jdbc3.jar"
    group=rundeck
    mode=0655
    owner=rundeck
  tags:
    - rundeck
    - jdbc
    - postgresql

- name: Rundeck - PostgreSQL | update database connection in configuration
  lineinfile: >
    dest=/etc/rundeck/rundeck-config.properties
    regexp="^dataSource.url"
    line="dataSource.url=jdbc:postgresql://{{ rundeck_database_host }}:{{ rundeck_database_port|default('5432') }}/{{ rundeck_database_name }}"
  notify:
    - restart rundeck
  tags:
    - rundeck
    - configuration
    - postgresql

- name: Rundeck - PostgreSQL | update database driver in configuration
  lineinfile: >
    dest=/etc/rundeck/rundeck-config.properties
    regexp="^dataSource.driverClassName"
    line="dataSource.driverClassName=org.postgresql.Driver"
  notify:
    - restart rundeck
  tags:
    - rundeck
    - configuration
    - postgresql

- name: Rundeck - PostgreSQL | update database dialect in configuration
  lineinfile: >
    dest=/etc/rundeck/rundeck-config.properties
    regexp="^dataSource.dialect"
    line="dataSource.dialect=org.hibernate.dialect.PostgreSQLDialect"
  notify:
    - restart rundeck
  tags:
    - rundeck
    - configuration
    - postgresql

- name: Rundeck - PostgreSQL | update database username in configuration
  lineinfile: >
    dest=/etc/rundeck/rundeck-config.properties
    regexp="^dataSource.username"
    line="dataSource.username={{ rundeck_database_user }}"
  notify:
    - restart rundeck
  tags:
    - rundeck
    - configuration
    - postgresql

- name: Rundeck - PostgreSQL | update database password in configuration
  lineinfile: >
    dest=/etc/rundeck/rundeck-config.properties
    regexp="^dataSource.password"
    line="dataSource.password={{ rundeck_database_pass }}"
  notify:
    - restart rundeck
  tags:
    - rundeck
    - configuration
    - postgresql

- name: Rundeck - PostgreSQL | ensure database is used to store projects
  lineinfile: >
    dest=/etc/rundeck/rundeck-config.properties
    line="rundeck.projectsStorageType=db"
    state="present"
  when: rundeck_targeting_version.stdout|version_compare('2.5.0', '>=')
  notify:
    - restart rundeck
  tags:
    - rundeck
    - configuration
    - postgresql
