---
- name: systemd daemon-reload
  become: yes
  command: systemctl daemon-reload
  when: ansible_service_mgr == 'systemd'

- name: start rundeck
  service: name=rundeckd state=started

- name: restart rundeck
  service: name=rundeckd state=restarted
